Vehicles = {
    ['GLOBAL'] = 170, 

-- X Class = 270 (RP Car 'not for sale')
-- S Class = 240
-- A Class = 220
-- B Class = 190
-- C Class = 170
-- M Class = 220


-- S Class Donation
    [GetHashKey('vercyskyline')] = 240,
    [GetHashKey('ikx3_xxs24b')] = 240,
    [GetHashKey('manscarreragt')] = 240,
    [GetHashKey('vercya80')] = 240,
    [GetHashKey('rmodlfa')] = 240,
    [GetHashKey('manssupersnake')] = 240,

-- S Class PDM
    [GetHashKey('coquette4')] = 235,
    [GetHashKey('tenf')] = 235,
    [GetHashKey('jester4')] = 235,
    [GetHashKey('deviant')] = 235,
    [GetHashKey('sultanrs')] = 235,
    [GetHashKey('tenf2')] = 235,
    [GetHashKey('comet7')] = 235, 
-- S Class Police

    [GetHashKey('fed18muscle')] = 240,
    [GetHashKey('fed20muscle')] = 240,
    [GetHashKey('fed18sedan')] = 240,

-- A Class Donation
    [GetHashKey('ikx3_civicr23b')] = 220,
    [GetHashKey('golf75r')] = 220,
    [GetHashKey('fk8hr')] = 220,
    [GetHashKey('benze55')] = 220,

-- A Class PDM
    [GetHashKey('boor')] = 220,
    [GetHashKey('deity')] = 220,
    [GetHashKey('cinquemila')] = 220,
    [GetHashKey('previon')] = 220,
    [GetHashKey('champion')] = 220,
    [GetHashKey('dominator3')] = 220,
    [GetHashKey('gauntlet4')] = 220,
    [GetHashKey('tampa2')] = 220,
    [GetHashKey('yosemite')] = 220,
    [GetHashKey('buffalo4')] = 220,
    [GetHashKey('infernus2')] = 220,
    [GetHashKey('savestra')] = 220,
    [GetHashKey('turismo2')] = 220,
    [GetHashKey('z190')] = 220,
    [GetHashKey('comet3')] = 220,
    [GetHashKey('drafter')] = 220,
    [GetHashKey('elegy')] = 220,
    [GetHashKey('feltzer2')] = 220, 
    [GetHashKey('imorgon')] = 220, 
    [GetHashKey('italigto')] = 220, 
    [GetHashKey('jugular')] = 220,
    [GetHashKey('jester3')] = 220,
    [GetHashKey('kuruma')] = 220,
    [GetHashKey('ninef')] = 220,
    [GetHashKey('penumbra2')] = 220,
    [GetHashKey('ruston')] = 220,
    [GetHashKey('specter')] = 220,
    [GetHashKey('seven70')] = 220,
    [GetHashKey('sultan3')] = 220,
    [GetHashKey('tailgater2')] = 220,
    [GetHashKey('euros')] = 220,
    [GetHashKey('vectre')] = 220,
    [GetHashKey('panthere')] = 220,
    [GetHashKey('bullet')] = 220,
    [GetHashKey('entity2')] = 220,
    [GetHashKey('entityxf')] = 220,
    [GetHashKey('emerus')] = 220,
    [GetHashKey('gp1')] = 220, 
    [GetHashKey('italigtb')] = 220, 
    [GetHashKey('osiris')] = 220, 
    [GetHashKey('t20')] = 220,
    [GetHashKey('tempesta')] = 220,
    [GetHashKey('vacca')] = 220,
    [GetHashKey('ignus')] = 220,


-- A Class Police
    [GetHashKey('fed14sedan')] = 220,
    [GetHashKey('fed13sedan')] = 220,
    [GetHashKey('fed13utility')] = 220,
    [GetHashKey('fed13utilityk9')] = 220,

-- B Class PDM
    [GetHashKey('club')] = 190,
    [GetHashKey('asbo')] = 190,
    [GetHashKey('blista2')] = 190,
    [GetHashKey('weevil')] = 190,
    [GetHashKey('issi8')] = 190,
    [GetHashKey('stratum')] = 190,
    [GetHashKey('warremer')] = 190,
    [GetHashKey('rhinehart')] = 190,
    [GetHashKey('iwagen')] = 190,
    [GetHashKey('astron')] = 190,
    [GetHashKey('granger')] = 190,
    [GetHashKey('sentinel3')] = 190,
    [GetHashKey('windsor')] = 190,
    [GetHashKey('zion')] = 190,
    [GetHashKey('futo')] = 190, 
    [GetHashKey('kanjosj')] = 190,
    [GetHashKey('postlude3')] = 190,
    [GetHashKey('coquette3')] = 190,
    [GetHashKey('dominator')] = 190,
    [GetHashKey('gauntlet3')] = 190,
    [GetHashKey('nightshade')] = 190,
    [GetHashKey('ruiner')] = 190,
    [GetHashKey('ardent')] = 190, 
    [GetHashKey('gt500')] = 190,
    [GetHashKey('mamba')] = 190,
    [GetHashKey('monroe')] = 190,
    [GetHashKey('stingergt')] = 190,
    [GetHashKey('banshee')] = 190,
    [GetHashKey('comet2')] = 190,
    [GetHashKey('elegy2')] = 190,
    [GetHashKey('flashgt')] = 190, 
    [GetHashKey('furoregt')] = 190, 
    [GetHashKey('gb200')] = 190,
    [GetHashKey('komoda')] = 190,
    [GetHashKey('lynx')] = 190,
    [GetHashKey('neon')] = 190,
    [GetHashKey('sugoi')] = 190,
    [GetHashKey('sultan')] = 190,
    [GetHashKey('vstr')] = 190, 
    [GetHashKey('calico')] = 190, 
    [GetHashKey('sentinel4')] = 190,
    [GetHashKey('dubsta3')] = 190,
    [GetHashKey('outlaw')] = 190,
    [GetHashKey('sandking')] = 190,
    [GetHashKey('trophytruck2')] = 190,

-- C Class PDM
    [GetHashKey('blista')] = 170,
    [GetHashKey('brioso')] = 170,
    [GetHashKey('dilettante')] = 170,
    [GetHashKey('issi2')] = 170,
    [GetHashKey('panto')] = 170,
    [GetHashKey('rhapsody')] = 170,
    [GetHashKey('prairie')] = 170,
    [GetHashKey('fugitive')] = 170,
    [GetHashKey('glendale2')] = 170,
    [GetHashKey('ingot')] = 170,
    [GetHashKey('cog55')] = 170,
    [GetHashKey('primo2')] = 170,
    [GetHashKey('stafford')] = 170,
    [GetHashKey('superd')] = 170,
    [GetHashKey('tailgater')] = 170, 
    [GetHashKey('warrener2')] = 170, 
    [GetHashKey('eudora')] = 170,
    [GetHashKey('baller2')] = 170,
    [GetHashKey('contender')] = 170,
    [GetHashKey('dubsta2')] = 170,
    [GetHashKey('landstalker2')] = 170,
    [GetHashKey('novak')] = 170,
    [GetHashKey('patriot2')] = 170,
    [GetHashKey('rebla')] = 170,
    [GetHashKey('toros')] = 170,
    [GetHashKey('felon')] = 170,
    [GetHashKey('jackal')] = 170,
    [GetHashKey('sentinel')] = 170,
    [GetHashKey('tahoma')] = 170,
    [GetHashKey('blade')] = 170,
    [GetHashKey('chino')] = 170,
    [GetHashKey('faction')] = 170, 
    [GetHashKey('hotknife')] = 170, 
    [GetHashKey('virgo2')] = 170,
    [GetHashKey('voodoo')] = 170,
    [GetHashKey('greenwood')] = 170,
    [GetHashKey('dynasty')] = 170,
    [GetHashKey('feltzer3')] = 170,
    [GetHashKey('jb7002')] = 170,
    [GetHashKey('nebula')] = 170,
    [GetHashKey('retinue')] = 170,
    [GetHashKey('cheburek')] = 170,
    [GetHashKey('bifta')] = 170,
    [GetHashKey('blazer')] = 170,
    [GetHashKey('dune')] = 170,
    [GetHashKey('kalahari')] = 170,
    [GetHashKey('bfinjection')] = 170,
    [GetHashKey('bison')] = 170,
    [GetHashKey('bobcatxl')] = 170, 
    [GetHashKey('burrito3')] = 170, 
    [GetHashKey('gburrito')] = 170,
    [GetHashKey('gburrito2')] = 170,
    [GetHashKey('speedo')] = 170,
    [GetHashKey('mule2')] = 170,
    [GetHashKey('mule3')] = 170,
    [GetHashKey('taco')] = 170,
    [GetHashKey('taxi')] = 170,

-- M Class Police

    [GetHashKey('fedmotor')] = 220,
    
-- M Class PDM

    [GetHashKey('akuma')] = 200,
    [GetHashKey('bagger2')] = 200,
    [GetHashKey('chimera')] = 200,
    [GetHashKey('cliffhanger')] = 200,
    [GetHashKey('daemon')] = 200,
    [GetHashKey('daemon2')] = 200,
    [GetHashKey('enduro')] = 200,
    [GetHashKey('faggio')] = 200,
    [GetHashKey('faggio2')] = 200,
    [GetHashKey('faggio3')] = 200,
    [GetHashKey('gargoyle')] = 200,
    [GetHashKey('hexer')] = 200,
    [GetHashKey('nightblade')] = 200,
    [GetHashKey('ratbike')] = 200,
    [GetHashKey('sanchez2')] = 200,
    [GetHashKey('wolfsbane')] = 200,
    [GetHashKey('sanctus')] = 200,
    [GetHashKey('zombiea')] = 200,

}